// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int32
	FirstName string
	LastName  sql.NullString
	UpdatedAt time.Time
}
